### ISSUE TITLE
Mention source / rights holder of images in about?

### ISSUE THREAD

**Issue by puckey** [nonlinearnarrative/no-home-like-place#18]
It would be good internet etiquette to mention the source of the images that we are using.. We could do so in the about section. The question is: who holds the rights of the images? The listing users? Airbnb?

**Comment by 0q98ahdsg3987y1h987y** [comment]
I can't find any information on this. Airbnb just mentions they are granting permission to themselves to use user generated content on their website. If you hire a professional photographer through Airbnb, the rights of the photo go to Airbnb. That's all I can find.

Probably falls under fair use, though
