### ISSUE TITLE
Outline for replacement pictures while loading?

### ISSUE THREAD

**Issue by 0q98ahdsg3987y1h987y** [nonlinearnarrative/no-home-like-place#2]
Right now on slow internet connections, there is no indication images are still loading. If the background has already loaded but none of the replacements, this is confusing because nothing seems clickable. Maybe we can add a white 1px outline that is removed when the image is loaded?

**Comment by puckey** [comment]
I added loading / placing feedback in the box on the bottom left – what do you think?

**Comment by 0q98ahdsg3987y1h987y** [comment]
Works very well I think
