### ISSUE TITLE
Replacement pictures sometimes fail to load entirely

### ISSUE THREAD

**Issue by 0q98ahdsg3987y1h987y** [nonlinearnarrative/no-home-like-place#3]
Sometimes a background will load but none of the replacement pictures will. It seems to happen if the `findClickedCrop` inside `onClick` returns a crop that does not have a `name` or `photo` attribute, which lets it skip the early return but causes a type error at line 294: `initialize(crop.photo.photoId);`

**Comment by puckey** [comment]
Is this still a thing?

**Comment by puckey** [comment]
Haven't noticed this happening anymore - please reopen if it is still an issue
