### ISSUE TITLE
Clicking a tag sometimes registers the tag below it instead

### ISSUE THREAD

**Issue by 0q98ahdsg3987y1h987y** [nonlinearnarrative/no-home-like-place#5]
If two tags are stacked on top of each other, e.g. a cup on a table, trying to click the cup will register as clicking the table instead.

**Comment by puckey** [comment]
I think I fixed this in the meantime – can you check?

**Comment by 0q98ahdsg3987y1h987y** [comment]
Tested about 50 rooms with no problems, closing
