### ISSUE TITLE
Tags sometimes do not line up

### ISSUE THREAD

**Issue by 0q98ahdsg3987y1h987y** [nonlinearnarrative/no-home-like-place#7]
Seems to be something weird with a horizontal translation / scale
<img width="1089" alt="screen shot 2018-05-11 at 22 39 32" src="https://user-images.githubusercontent.com/6472410/39946035-ef35c7c6-556c-11e8-92f2-d872f21604b6.png">

**Comment by puckey** [comment]
Can you check if this is a problem in the object detection data?

**Comment by 0q98ahdsg3987y1h987y** [comment]
Can't seem to reproduce anymore... I'll update if I see it again

**Comment by 0q98ahdsg3987y1h987y** [comment]
Here's a room where the issue shows up consistently https://nonlinearnarrative.github.io/no-home-like-place/#244-2

**Comment by puckey** [comment]
I updated the imagery to the world scrape now, which killed your link.. I am wondering if the image detection algorithm has some quirks.. Could you:
- find a page which doesn't work
- use the network inspector to find out which listing & image it is
- take a look at the object detection data to see if those rectangles line up with the objects in the image

**Comment by puckey** [comment]
This was an issue on my side - should be fixed now.
